spring:
  application:
    name: first-server

server:
  port: 8443
#  ssl:
#    enabled: true
#    key-store: classpath:/certs/first-server.p12
#    key-store-password: changeit
#    key-store-type: PKCS12
#    key-alias: first-server

#gateway:
#  ssl:
#    key-store: classpath:/certs/first-server.p12
#    key-store-password: changeit
#    trust-store: classpath:/certs/truststore.p12
#    trust-store-password: changeit