spring:
  application:
    name: second-server

server:
  port: 8444
#  ssl:
#    enabled: true
#    key-store: classpath:/certs/second-server.p12
#    key-store-password: changeit
#    key-store-type: PKCS12
#    key-alias: second-server
#    trust-store: classpath:/certs/truststore.p12
#    trust-store-password: changeit
#    trust-store-type: PKCS12
#    client-auth: need
